stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingestion.py
    deps:
      - src/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/extracted_data
      - artifacts/data_ingestion/raw_data
  
  prepare_base_model:
    cmd: python src/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepared_base_model

  training:
    cmd: python src/pipeline/stage_03_model_trainer.py
    deps:
      - src/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/extracted_data/Chest-CT-Scan-data
      - artifacts/prepared_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/trained_model/model.h5
